In [1]:
import os
import pandas as pd
from identify_home import HomeLocationIdentifier
import geopandas as gpd

In [2]:
pwd

'/Users/gracejia/Documents/A-UW/dissertation/street_furniture/escience/MAWpy/src/mawpy/utilities'

In [2]:
# Define test file paths
test_input_file = '10_users.csv'
test_shapefile = 'cb_2022_us_tract_500k/cb_2022_us_tract_500k.shp'
test_output_file = '10_users_home_locations.csv'

In [3]:
# Read input data
input_data = pd.read_csv(test_input_file)
# contain only the four mandatory columns user_ID, unix_start_t, orig_lat and orig_long
input_data = input_data[['user_ID', 'unix_start_t', 'orig_lat', 'orig_long']]

tracts = gpd.read_file(test_shapefile)

In [5]:
tracts.columns

Index(['STATEFP', 'COUNTYFP', 'TRACTCE', 'AFFGEOID', 'GEOID', 'NAME',
       'NAMELSAD', 'STUSPS', 'NAMELSADCO', 'STATE_NAME', 'LSAD', 'ALAND',
       'AWATER', 'geometry'],
      dtype='object')

In [4]:


# Instantiate the HomeLocationIdentifier with test data
identifier = HomeLocationIdentifier(test_input_file, test_shapefile, test_output_file)

# Run the process
identifier.run()

# Check the output
output_df = pd.read_csv(test_output_file)
print(output_df)

# # Clean up test files
# os.remove(test_input_file)
# os.remove(test_output_file)
# # Remove the shapefile if it was created for testing
# # os.remove('test_shapefile.shp')

Loaded data contains 10 unique user IDs.
Nighttime data contains 175 records after filtering.
Nighttime data contains 10 unique user IDs.
User IDs with nighttime data: ['f98247efb013243c91c247aa6c6e119e71404a698005d1e3ee7654f17130cb25'
 '2625647e11173f95ef14599c4835355cfe2f492adb3a2e1a7a47748760345612'
 '3ab7c1282d7c0ed632f93d6ca1c81ef0bf74351f50b8cb9eafe4167004ca373a'
 'd01a212a23148fa52244ce75d247e35d53f96cd6d8b353b0b3e37a873e955527'
 'f32492e1387ee27bb34969fb5988bf48324408295372721b9bd7b4816a9cedf4'
 '6db93f996408d398cebdb6ef77e68f88aaafc714d4ff05d914fcc4397eb8e94c'
 '3ea9e7e79431fc8fcc2fb447ee0dfc6a9fca74cc9e54558b80785b8577f6f37f'
 '97c849caf2367a58377e946eb575484fc691e6eb7bb15ceeed48b72ff7d9c64e'
 '40e27edbc0d0b5684d5fe2ca909e0b70fc05910370d862c149a20cdd93637972'
 '5b60012041533aca8a11b86cc391e1ae0ca7e0a9de6e2eadba332b6d66825bf6']
Days available for each user:
                                             user_ID  number_of_days  \
0  2625647e11173f95ef14599c4835355cfe2f492adb3a2e...               3
1  3ab7c1282d7c0ed632f93d6ca1c81ef0bf74351f50b8cb...               3
2  3ea9e7e79431fc8fcc2fb447ee0dfc6a9fca74cc9e5455...               1
3  40e27edbc0d0b5684d5fe2ca909e0b70fc05910370d862...               1
4  5b60012041533aca8a11b86cc391e1ae0ca7e0a9de6e2e...               5
5  6db93f996408d398cebdb6ef77e68f88aaafc714d4ff05...              11
6  97c849caf2367a58377e946eb575484fc691e6eb7bb15c...               2
7  d01a212a23148fa52244ce75d247e35d53f96cd6d8b353...               2
8  f32492e1387ee27bb34969fb5988bf4832440829537272...               6
9  f98247efb013243c91c247aa6c6e119e71404a698005d1...               5

   min_visits
0           0
1           0
2           0
3           0
4           2
5           3
6           0
7           0
8           2
9           2
Joined GeoDataFrame contains 175 records.
Visit counts:
                                              user_ID        GEOID  \
0   2625647e11173f95ef14599c4835355cfe2f492adb3a2e...  53053073111
1   2625647e11173f95ef14599c4835355cfe2f492adb3a2e...  53053073116
2   2625647e11173f95ef14599c4835355cfe2f492adb3a2e...  53053073119
3   2625647e11173f95ef14599c4835355cfe2f492adb3a2e...  53053073123
4   2625647e11173f95ef14599c4835355cfe2f492adb3a2e...  53053073200
..                                                ...          ...
60  f32492e1387ee27bb34969fb5988bf4832440829537272...  53033032331
61  f98247efb013243c91c247aa6c6e119e71404a698005d1...  53033005401
62  f98247efb013243c91c247aa6c6e119e71404a698005d1...  53033009300
63  f98247efb013243c91c247aa6c6e119e71404a698005d1...  53061040100
64  f98247efb013243c91c247aa6c6e119e71404a698005d1...  53061940001

    visit_count  number_of_days  min_visits
0             1               3           0
1             2               3           0
2             1               3           0
3             1               3           0
4             2               3           0
..          ...             ...         ...
60            2               6           2
61            1               5           2
62            1               5           2
63            4               5           2
64            1               5           2

[65 rows x 5 columns]
Home locations:
                                              user_ID        GEOID  \
1   2625647e11173f95ef14599c4835355cfe2f492adb3a2e...  53053073116
7   3ab7c1282d7c0ed632f93d6ca1c81ef0bf74351f50b8cb...  53033026200
15  3ea9e7e79431fc8fcc2fb447ee0dfc6a9fca74cc9e5455...  53033028402
17  40e27edbc0d0b5684d5fe2ca909e0b70fc05910370d862...  53033026400
19  5b60012041533aca8a11b86cc391e1ae0ca7e0a9de6e2e...  53033010602
30  6db93f996408d398cebdb6ef77e68f88aaafc714d4ff05...  53053071304
41  97c849caf2367a58377e946eb575484fc691e6eb7bb15c...  53033005804
52  d01a212a23148fa52244ce75d247e35d53f96cd6d8b353...  53053072903
59  f32492e1387ee27bb34969fb5988bf4832440829537272...  53033032316
63  f98247efb013243c91c247aa6c6e119e71404a698005d1...  53061040100

    visit_count  number_of_days  min_visits
1             2               3           0
7             4               3           0
15            4               1           0
17            1               1           0
19            3               5           2
30           31              11           3
41            4               2           0
52            4               2           0
59            2               6           2
63            4               5           2
                                             user_ID        GEOID  \
0  2625647e11173f95ef14599c4835355cfe2f492adb3a2e...  53053073116
1  3ab7c1282d7c0ed632f93d6ca1c81ef0bf74351f50b8cb...  53033026200
2  3ea9e7e79431fc8fcc2fb447ee0dfc6a9fca74cc9e5455...  53033028402
3  40e27edbc0d0b5684d5fe2ca909e0b70fc05910370d862...  53033026400
4  5b60012041533aca8a11b86cc391e1ae0ca7e0a9de6e2e...  53033010602
5  6db93f996408d398cebdb6ef77e68f88aaafc714d4ff05...  53053071304
6  97c849caf2367a58377e946eb575484fc691e6eb7bb15c...  53033005804
7  d01a212a23148fa52244ce75d247e35d53f96cd6d8b353...  53053072903
8  f32492e1387ee27bb34969fb5988bf4832440829537272...  53033032316
9  f98247efb013243c91c247aa6c6e119e71404a698005d1...  53061040100

   number_of_days  visit_count
0               3            2
1               3            4
2               1            4
3               1            1
4               5            3
5              11           31
6               2            4
7               2            4
8               6            2
9               5            4

/Users/gracejia/Documents/A-UW/dissertation/street_furniture/escience/MAWpy/src/mawpy/utilities/identify_home.py:70: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.night_data['date'] = self.night_data['datetime'].dt.date

In [5]:
identifier.night_data

,Unnamed: 0,unix_start_t,user_ID,mark_1,orig_lat,orig_long,orig_unc,stay_lat,stay_long,stay_unc,stay_dur,stay_ind,human_start_t,datetime,hour,date
0,0,1552522827,f98247efb013243c91c247aa6c6e119e71404a698005d1...,0,47.651589,-122.327397,900,-1,-1,-1,-1,-1,1.903130e+11,2019-03-14 00:20:27,0,2019-03-14
3,3,1553827223,f98247efb013243c91c247aa6c6e119e71404a698005d1...,0,47.590755,-122.330222,103,-1,-1,-1,-1,-1,1.903280e+11,2019-03-29 02:40:23,2,2019-03-29
5,5,1554524949,f98247efb013243c91c247aa6c6e119e71404a698005d1...,0,48.081200,-122.185132,1300,-1,-1,-1,-1,-1,1.904050e+11,2019-04-06 04:29:09,4,2019-04-06
10,10,1555020423,f98247efb013243c91c247aa6c6e119e71404a698005d1...,0,47.995571,-122.222558,104,-1,-1,-1,-1,-1,1.904110e+11,2019-04-11 22:07:03,22,2019-04-11
11,11,1555021060,f98247efb013243c91c247aa6c6e119e71404a698005d1...,0,47.999322,-122.222172,104,-1,-1,-1,-1,-1,1.904110e+11,2019-04-11 22:17:40,22,2019-04-11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
467,467,1555893180,5b60012041533aca8a11b86cc391e1ae0ca7e0a9de6e2e...,1,47.554809,-122.399418,165,-1,-1,-1,-1,-1,1.904210e+11,2019-04-22 00:33:00,0,2019-04-22
469,469,1572928357,5b60012041533aca8a11b86cc391e1ae0ca7e0a9de6e2e...,1,47.544861,-122.387514,165,-1,-1,-1,-1,-1,1.911040e+11,2019-11-05 04:32:37,4,2019-11-05
470,470,1572928752,5b60012041533aca8a11b86cc391e1ae0ca7e0a9de6e2e...,1,47.545105,-122.387461,165,-1,-1,-1,-1,-1,1.911040e+11,2019-11-05 04:39:12,4,2019-11-05
471,471,1572928936,5b60012041533aca8a11b86cc391e1ae0ca7e0a9de6e2e...,1,47.537231,-122.383966,165,-1,-1,-1,-1,-1,1.911040e+11,2019-11-05 04:42:16,4,2019-11-05
472,472,1573784295,5b60012041533aca8a11b86cc391e1ae0ca7e0a9de6e2e...,1,47.567474,-122.365098,165,-1,-1,-1,-1,-1,1.911140e+11,2019-11-15 02:18:15,2,2019-11-15

In [6]:
identifier.night_data.user_ID.nunique()

10

In [5]:
input_data.user_ID.nunique()

10